CREATE OR REPLACE PROCEDURE GOLD.CALCULATE_CUSTOMER_CHURN_RATE(PERIOD_DAYS INT)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    TOTAL_CUSTOMERS INT;
    CHURNED_CUSTOMERS INT;
    CHURN_RATE FLOAT;
BEGIN
    -- Count total active customers
    SELECT COUNT(DISTINCT CUSTOMER_ID)
      INTO :TOTAL_CUSTOMERS
    FROM CURATED.CUSTOMERS_CURATED;

    -- Count churned customers (no recent orders in last PERIOD_DAYS)
    SELECT COUNT(DISTINCT C.CUSTOMER_ID)
      INTO :CHURNED_CUSTOMERS
    FROM CURATED.CUSTOMERS_CURATED C
    LEFT JOIN CURATED.ORDERS_CURATED S
      ON C.CUSTOMER_ID = S.CUSTOMER_ID
      AND S.ORDER_DATE >= DATEADD('DAY', :PERIOD_DAYS, CURRENT_DATE())
    WHERE S.CUSTOMER_ID IS NULL;

    -- Calculate churn rate
    SELECT ROUND((:CHURNED_CUSTOMERS::FLOAT / NULLIF(:TOTAL_CUSTOMERS, 0)::FLOAT) * 100, 2)
      INTO :CHURN_RATE;

    -- Log results
    INSERT INTO GOLD.CUSTOMER_CHURN_HISTORY (RUN_DATE, PERIOD_DAYS, TOTAL, CHURNED, RATE)
    VALUES (CURRENT_DATE(), :PERIOD_DAYS, :TOTAL_CUSTOMERS, :CHURNED_CUSTOMERS, :CHURN_RATE);

    RETURN OBJECT_CONSTRUCT(
        'period_days', PERIOD_DAYS,
        'total_customers', :TOTAL_CUSTOMERS,
        'churned_customers', :CHURNED_CUSTOMERS,
        'churn_rate_percent', :CHURN_RATE
    );
END;
$$;


--CALL GOLD.CALCULATE_CUSTOMER_CHURN_RATE(70);
